server:
  port: 8180

# Actuator
management:
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: health,info,loggers,metrics,mappings

# With this config you can check swagger at http://localhost:8180/insurance-connector/swagger-ui-custom.html
springdoc:
  webflux:
    base-path: /insurance-connector
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    url: /v3/api-docs

# Application
spring:
  profiles:
    active: ${ENVIRONMENT}
  lifecycle:
    timeout-per-shutdown-phase: ${TIMEOUT_PER_SHUTDOWN_PHASE:30s}
  application:
    name: insurance-connector
  webflux:
    base-path: /insurance-connector

#Logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} | marker=%marker |  clientId=%X{clientId} | level=%5p | thread=%thread | traceId=%X{traceId} spanId=%X{spanId} |  projectVersion=%X{projectVersion} |class=%class{15}.%L | msg="%.-50000m"%n'

# Custom properties #
http-client:
  timeout: ${REQUEST_TIMEOUT:15}
  #Number of retries if external communication fails
  retry: ${REQUEST_RETRY:3}
  #Duration in seconds between retries
  duration: ${REQUEST_DURATION:2}

busqo:
  config: ${BUSQO_CONFIG}
  offerUrl: /Quote

# Thycotic
secrets-provider:
  sdk:
    http-client:
      host: ${BASE_URL}
      connection-timeout-in-seconds: 5
      read-timeout-in-seconds: 10
      max-idle-connections: 5
      keep-alive-duration-in-seconds: 360
      ttl-token-cache-in-seconds: 360
    idp:
      idp-url-token: ${IDP_URL_TOKEN}
      idp-client-id: ${IDP_CLIENT_ID_SECRET_NAME}
      idp-client-secret: ${IDP_CLIENT_SECRET_SECRET_NAME}
  bootstrap:
    app: insurance-connector
    bucket-name: ${CONFIG_SERVER_BUCKET_NAME}